name: heart-rate-monitor_env
dependencies:
        - python=3.6
        - numpy
        - ipython
        - pytest
        - pytest-pep8
        - pytest-cov
        - sphinx
        - pandas
        - scipy
